
namespace ErrorCode {
	enum {
		ERROR_CODE_NO_ERROR = -1,
	};
	enum RegisterError {
		REGISTER_ERROR_NAME_ALREADY_EXIST = 105,
		REGISTER_ERROR_NAME_NAME_ILLEGAL = 106,
		REGISTER_ERROR_NAME_NAME_TOO_LONG = 107,
		REGISTER_ERROR_FAIL = 111,
		REGISTER_PASSWD_ILLEGAL = 129,
		REGISTER_ERROR_PASSWD_NAME_TOO_LONG = 132
	};
	enum LoginError {
		LOGIN_ERROR_ONLINE_FULL = 101,
		LOGIN_ERROR_SERVER_NOT_SELECTED = 103,
		LOGIN_ERROR_ACCOUNT_NON_EXIST = 108,
		LOGIN_ERROR_NAME_PASSWD_ERROR = 109,
		LOGIN_ERROR_ACCOUNT_FROZEN = 110,
		LOGIN_ERROR_NICK_NAME_ALREADY_EXIST = 112,
	};
	enum {
		ERROR_NO_ENOUGH_MONEY = 121,
		ERROR_LEVEL_TOO_LOW = 147
	};
	enum {
		BUY_ITEM_ERROR_ITEM_BAG_FULL = 146,
		BUY_ITEM_ERROR_NO_ENOUGH_MONEY = 152
	};

	enum {
		STRENGTH_GEM_NO_ENOUGH_FRAGMENT = 158,
		STRENGTH_EQUIP_ERROR_ROLE_LEVEL_TO_HIGH = 200,
		STRENGTH_EQUIP_ERROR_FAIL = 201,
	};
}
